[greeter]
background=/usr/share/backgrounds/stradilabos/stradilabos-wallpaper-v3.png
user-background=false
theme-name=StradiLab
icon-theme-name=StradiLab
font-name=Noto Sans 11
xft-antialias=true
xft-hintstyle=hintslight
position=18% 48%
default-user-image=#stradilabos
hide-user-image=false
clock-format=%A %d %B · %H:%M
indicators=~host;~spacer;~clock;~spacer;~language;~session;~a11y;~power
