#!/bin/sh
set -eu

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-recommends true \
    --updates true \
    --firmware-binary true \
    --firmware-chroot true \
    --debian-installer none \
    --bootappend-live "boot=live components username=stradi hostname=stradilabos locales=it_IT.UTF-8 keyboard-layouts=it timezone=Europe/Rome utc=yes quiet splash" \
    --iso-application "StradilabOS Live" \
    --iso-publisher "StradiLab - IIS Antonio Stradivari Cremona" \
    --iso-volume "STRADILABOS" \
    --image-name "stradilabos-live" \
    "$@"
